import logging
from typing import Final

DOMAIN = "dreame_vacuum"
LOGGER = logging.getLogger(__package__)

UNIT_MINUTES: Final = "min"
UNIT_HOURS: Final = "h"
UNIT_PERCENT: Final = "%"
UNIT_DAYS: Final = "d"
UNIT_AREA: Final = "m²"

CONF_NOTIFY: Final = "notify"
CONF_COLOR_SCHEME: Final = "color_scheme"
CONF_ICON_SET: Final = "icon_set"
CONF_COUNTRY: Final = "country"
CONF_TYPE: Final = "configuration_type"
CONF_MAC: Final = "mac"
CONF_DID: Final = "did"
CONF_AUTH_KEY: Final = "auth_key"
CONF_MAP_OBJECTS: Final = "map_objects"
CONF_HIDDEN_MAP_OBJECTS: Final = "hidden_map_objects"
CONF_PREFER_CLOUD: Final = "prefer_cloud"
CONF_LOW_RESOLUTION: Final = "low_resolution"
CONF_SQUARE: Final = "square"
CONF_ACCOUNT_TYPE: Final = "account_type"
CONF_VERSION: Final = "version"

MAP_OBJECTS: Final = ["color", "icon", "name", "name_background", "order", "suction_level", "water_volume", "cleaning_times", "cleaning_mode", "mopping_mode", "path", "no_go", "no_mop", "virtual_wall", "pathway", "active_area", "active_point", "charger", "robot", "cleaning_direction", "obstacle", "pet", "carpet", "material", "low_lying_area", "furniture", "ramp", "curtain", "cruise_point"]
NOTIFICATION: Final = ["cleanup_completed", "consumable", "information", "warning", "error"]

CONSUMABLE_MAIN_BRUSH = "main_brush"
CONSUMABLE_SIDE_BRUSH = "side_brush"
CONSUMABLE_FILTER = "filter"
CONSUMABLE_TANK_FILTER = "tank_filter"
CONSUMABLE_SENSOR = "sensor"
CONSUMABLE_MOP_PAD = "mop_pad"
CONSUMABLE_SILVER_ION = "silver_ion"
CONSUMABLE_DETERGENT = "detergent"
CONSUMABLE_SQUEEGEE = "squeegee"
CONSUMABLE_ONBOARD_DIRTY_WATER_TANK = "onboard_dirty_water_tank"
CONSUMABLE_DIRTY_WATER_CHANNEL = "dirty_water_channel"
CONSUMABLE_DEODORIZER = "deodorizer"
CONSUMABLE_WHEEL = "wheel"
CONSUMABLE_SCALE_INHIBITOR = "scale_inhibitor"
CONSUMABLE_FLUFFING_ROLLER = "fluffing_roller"
CONSUMABLE_ROLLER_MOP_FILTER = "roller_mop_filter"
CONSUMABLE_WATER_OUTLET_FILTER = "water_outlet_filter"

NOTIFICATION_ID_DUST_COLLECTION: Final = "dust_collection"
NOTIFICATION_ID_CLEANING_PAUSED: Final = "cleaning_paused"
NOTIFICATION_ID_REPLACE_MAIN_BRUSH: Final = "replace_main_brush"
NOTIFICATION_ID_REPLACE_SIDE_BRUSH: Final = "replace_side_brush"
NOTIFICATION_ID_REPLACE_FILTER: Final = "replace_filter"
NOTIFICATION_ID_REPLACE_TANK_FILTER: Final = "replace_tank_filter"
NOTIFICATION_ID_CLEAN_SENSOR: Final = "clean_sensor"
NOTIFICATION_ID_REPLACE_MOP: Final = "replace_mop"
NOTIFICATION_ID_SILVER_ION: Final = "silver_ion"
NOTIFICATION_ID_REPLACE_DETERGENT: Final = "replace_detergent"
NOTIFICATION_ID_REPLACE_SQUEEGEE: Final = "replace_squeegee"
NOTIFICATION_ID_CLEAN_ONBOARD_DIRTY_WATER_TANK: Final = "clean_onboard_dirty_water_tank"
NOTIFICATION_ID_CLEAN_DIRTY_WATER_CHANNEL: Final = "clean_dirty_water_channel"
NOTIFICATION_ID_REPLACE_DEODORIZER = "replace_deodorizer"
NOTIFICATION_ID_CLEAN_WHEEL = "clean_wheel"
NOTIFICATION_ID_REPLACE_SCALE_INHIBITOR = "replace_scale_inhibitor"
NOTIFICATION_ID_CLEAN_FLUFFING_ROLLER = "clean_fluffing_roller"
NOTIFICATION_ID_CLEAN_ROLLER_MOP_FILTER = "clean_roller_mop_filter"
NOTIFICATION_ID_CLEAN_WATER_OUTLET_FILTER = "clean_water_outlet_filter"
NOTIFICATION_ID_CLEANUP_COMPLETED: Final = "cleanup_completed"
NOTIFICATION_ID_WARNING: Final = "warning"
NOTIFICATION_ID_ERROR: Final = "error"
NOTIFICATION_ID_INFORMATION: Final = "information"
NOTIFICATION_ID_CONSUMABLE: Final = "consumable"
NOTIFICATION_ID_REPLACE_TEMPORARY_MAP: Final = "replace_temporary_map"
NOTIFICATION_ID_LOW_WATER: Final = "low_water"
NOTIFICATION_ID_DRAINAGE_STATUS: Final = "drainage_status"

